package com.sandbox.service.two.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Sep 29 15:43:54 EDT 2011
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://www.thesearchagency.com/SandboxServiceTwo/", name = "SandboxServiceTwo")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SandboxServiceTwo {

    @WebMethod
    public void sandboxServiceTwoEcho();
}
