
/*
 * 
 */

package com.sandbox.service.two.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Sep 29 15:43:54 EDT 2011
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "SandboxServiceTwo", 
                  wsdlLocation = "file:/home/kbober/projects/sandbox/sandbox-service-two-soap-client/src/main/wsdl/SandboxServiceTwo-0.0.1-SNAPSHOT.wsdl",
                  targetNamespace = "http://www.thesearchagency.com/SandboxServiceTwo/") 
public class SandboxServiceTwo_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.thesearchagency.com/SandboxServiceTwo/", "SandboxServiceTwo");
    public final static QName SandboxServiceTwoPort = new QName("http://www.thesearchagency.com/SandboxServiceTwo/", "SandboxServiceTwoPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/kbober/projects/sandbox/sandbox-service-two-soap-client/src/main/wsdl/SandboxServiceTwo-0.0.1-SNAPSHOT.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/home/kbober/projects/sandbox/sandbox-service-two-soap-client/src/main/wsdl/SandboxServiceTwo-0.0.1-SNAPSHOT.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SandboxServiceTwo_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SandboxServiceTwo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SandboxServiceTwo_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns SandboxServiceTwo
     */
    @WebEndpoint(name = "SandboxServiceTwoPort")
    public SandboxServiceTwo getSandboxServiceTwoPort() {
        return super.getPort(SandboxServiceTwoPort, SandboxServiceTwo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SandboxServiceTwo
     */
    @WebEndpoint(name = "SandboxServiceTwoPort")
    public SandboxServiceTwo getSandboxServiceTwoPort(WebServiceFeature... features) {
        return super.getPort(SandboxServiceTwoPort, SandboxServiceTwo.class, features);
    }

}
