package com.sandbox.service.two.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-09T16:02:46.568-04:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sandbox.com/SandboxServiceTwo/", name = "SandboxServiceTwo")
@XmlSeeAlso({ObjectFactory.class})
public interface SandboxServiceTwo {

    @RequestWrapper(localName = "sandboxServiceTwoEcho", targetNamespace = "http://www.sandbox.com/SandboxServiceTwo/", className = "com.sandbox.service.two.soap.client.SandboxServiceTwoEcho")
    @WebMethod
    @ResponseWrapper(localName = "sandboxServiceTwoEchoResponse", targetNamespace = "http://www.sandbox.com/SandboxServiceTwo/", className = "com.sandbox.service.two.soap.client.SandboxServiceTwoEchoResponse")
    public void sandboxServiceTwoEcho();
}
