package com.sandbox.service.two.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-09T16:02:46.586-04:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "SandboxServiceTwo", 
                  wsdlLocation = "file:/home/kbober/repositories/sandbox/My-Sandbox/sandbox/sandbox-service/sandbox-service-two-parent/sandbox-service-two-soap-client/src/main/wsdl/SandboxServiceTwo-0.0.1-SNAPSHOT.wsdl",
                  targetNamespace = "http://www.sandbox.com/SandboxServiceTwo/") 
public class SandboxServiceTwo_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.sandbox.com/SandboxServiceTwo/", "SandboxServiceTwo");
    public final static QName SandboxServiceTwoPort = new QName("http://www.sandbox.com/SandboxServiceTwo/", "SandboxServiceTwoPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/kbober/repositories/sandbox/My-Sandbox/sandbox/sandbox-service/sandbox-service-two-parent/sandbox-service-two-soap-client/src/main/wsdl/SandboxServiceTwo-0.0.1-SNAPSHOT.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SandboxServiceTwo_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/kbober/repositories/sandbox/My-Sandbox/sandbox/sandbox-service/sandbox-service-two-parent/sandbox-service-two-soap-client/src/main/wsdl/SandboxServiceTwo-0.0.1-SNAPSHOT.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SandboxServiceTwo_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SandboxServiceTwo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SandboxServiceTwo_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SandboxServiceTwo
     */
    @WebEndpoint(name = "SandboxServiceTwoPort")
    public SandboxServiceTwo getSandboxServiceTwoPort() {
        return super.getPort(SandboxServiceTwoPort, SandboxServiceTwo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SandboxServiceTwo
     */
    @WebEndpoint(name = "SandboxServiceTwoPort")
    public SandboxServiceTwo getSandboxServiceTwoPort(WebServiceFeature... features) {
        return super.getPort(SandboxServiceTwoPort, SandboxServiceTwo.class, features);
    }

}
