package com.sandbox.service.one.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-09T16:02:41.535-04:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "SandboxServiceOne", 
                  wsdlLocation = "file:/home/kbober/repositories/sandbox/My-Sandbox/sandbox/sandbox-service/sandbox-service-one-parent/sandbox-service-one-soap-client/src/main/wsdl/SandboxServiceOne-0.0.1-SNAPSHOT.wsdl",
                  targetNamespace = "http://www.sandbox.com/SandboxServiceOne/") 
public class SandboxServiceOne_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.sandbox.com/SandboxServiceOne/", "SandboxServiceOne");
    public final static QName SandboxServiceOnePort = new QName("http://www.sandbox.com/SandboxServiceOne/", "SandboxServiceOnePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/kbober/repositories/sandbox/My-Sandbox/sandbox/sandbox-service/sandbox-service-one-parent/sandbox-service-one-soap-client/src/main/wsdl/SandboxServiceOne-0.0.1-SNAPSHOT.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SandboxServiceOne_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/kbober/repositories/sandbox/My-Sandbox/sandbox/sandbox-service/sandbox-service-one-parent/sandbox-service-one-soap-client/src/main/wsdl/SandboxServiceOne-0.0.1-SNAPSHOT.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SandboxServiceOne_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SandboxServiceOne_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SandboxServiceOne_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SandboxServiceOne
     */
    @WebEndpoint(name = "SandboxServiceOnePort")
    public SandboxServiceOne getSandboxServiceOnePort() {
        return super.getPort(SandboxServiceOnePort, SandboxServiceOne.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SandboxServiceOne
     */
    @WebEndpoint(name = "SandboxServiceOnePort")
    public SandboxServiceOne getSandboxServiceOnePort(WebServiceFeature... features) {
        return super.getPort(SandboxServiceOnePort, SandboxServiceOne.class, features);
    }

}
