package com.sandbox.service.one.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-09T16:02:41.527-04:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.sandbox.com/SandboxServiceOne/", name = "SandboxServiceOne")
@XmlSeeAlso({ObjectFactory.class})
public interface SandboxServiceOne {

    @RequestWrapper(localName = "executePentahoJob", targetNamespace = "http://www.sandbox.com/SandboxServiceOne/", className = "com.sandbox.service.one.soap.client.ExecutePentahoJob")
    @WebMethod
    @ResponseWrapper(localName = "executePentahoJobResponse", targetNamespace = "http://www.sandbox.com/SandboxServiceOne/", className = "com.sandbox.service.one.soap.client.ExecutePentahoJobResponse")
    public void executePentahoJob(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "testSpringDI", targetNamespace = "http://www.sandbox.com/SandboxServiceOne/", className = "com.sandbox.service.one.soap.client.TestSpringDI")
    @WebMethod
    @ResponseWrapper(localName = "testSpringDIResponse", targetNamespace = "http://www.sandbox.com/SandboxServiceOne/", className = "com.sandbox.service.one.soap.client.TestSpringDIResponse")
    public void testSpringDI();

    @RequestWrapper(localName = "executePentahoTransformation", targetNamespace = "http://www.sandbox.com/SandboxServiceOne/", className = "com.sandbox.service.one.soap.client.ExecutePentahoTransformation")
    @WebMethod
    @ResponseWrapper(localName = "executePentahoTransformationResponse", targetNamespace = "http://www.sandbox.com/SandboxServiceOne/", className = "com.sandbox.service.one.soap.client.ExecutePentahoTransformationResponse")
    public void executePentahoTransformation(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "sandboxServiceOneEcho", targetNamespace = "http://www.sandbox.com/SandboxServiceOne/", className = "com.sandbox.service.one.soap.client.SandboxServiceOneEcho")
    @WebMethod
    @ResponseWrapper(localName = "sandboxServiceOneEchoResponse", targetNamespace = "http://www.sandbox.com/SandboxServiceOne/", className = "com.sandbox.service.one.soap.client.SandboxServiceOneEchoResponse")
    public void sandboxServiceOneEcho();
}
