
/*
 * 
 */

package com.sandbox.service.one.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Thu Sep 29 15:43:53 EDT 2011
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "SandboxServiceOne", 
                  wsdlLocation = "file:/home/kbober/projects/sandbox/sandbox-service-one-soap-client/src/main/wsdl/SandboxServiceOne-0.0.1-SNAPSHOT.wsdl",
                  targetNamespace = "http://www.thesearchagency.com/SandboxServiceOne/") 
public class SandboxServiceOne_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.thesearchagency.com/SandboxServiceOne/", "SandboxServiceOne");
    public final static QName SandboxServiceOnePort = new QName("http://www.thesearchagency.com/SandboxServiceOne/", "SandboxServiceOnePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/kbober/projects/sandbox/sandbox-service-one-soap-client/src/main/wsdl/SandboxServiceOne-0.0.1-SNAPSHOT.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/home/kbober/projects/sandbox/sandbox-service-one-soap-client/src/main/wsdl/SandboxServiceOne-0.0.1-SNAPSHOT.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SandboxServiceOne_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SandboxServiceOne_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SandboxServiceOne_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns SandboxServiceOne
     */
    @WebEndpoint(name = "SandboxServiceOnePort")
    public SandboxServiceOne getSandboxServiceOnePort() {
        return super.getPort(SandboxServiceOnePort, SandboxServiceOne.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SandboxServiceOne
     */
    @WebEndpoint(name = "SandboxServiceOnePort")
    public SandboxServiceOne getSandboxServiceOnePort(WebServiceFeature... features) {
        return super.getPort(SandboxServiceOnePort, SandboxServiceOne.class, features);
    }

}
